
CREATE TABLE course
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    teacher_id  BIGINT,
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    status      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);

CREATE TABLE enrollment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id  BIGINT,
    course_id   BIGINT,
    enrolled_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_enrollment PRIMARY KEY (id)
);

CREATE TABLE lesson
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id     BIGINT,
    date          TIMESTAMP WITHOUT TIME ZONE,
    topic         VARCHAR(255),
    duration      BIGINT,
    materials_url VARCHAR(255),
    CONSTRAINT pk_lesson PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT,
    amount     DECIMAL,
    status     VARCHAR(255),
    date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE student
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name       VARCHAR(255),
    email           VARCHAR(255),
    phone           VARCHAR(255),
    enrollment_date TIMESTAMP WITHOUT TIME ZONE,
    status          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE teacher
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name      VARCHAR(255),
    email          VARCHAR(255),
    phone          VARCHAR(255),
    specialization VARCHAR(255),
    CONSTRAINT pk_teacher PRIMARY KEY (id)
);


ALTER TABLE course
    ADD CONSTRAINT FK_COURSE_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher (id);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE enrollment
    ADD CONSTRAINT FK_ENROLLMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE lesson
    ADD CONSTRAINT FK_LESSON_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);