CREATE TABLE auth_refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    token      VARCHAR(255),
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_authrefreshtoken PRIMARY KEY (id)
);


CREATE TABLE tenant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    subdomain  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    status     BOOLEAN                                 NOT NULL,
    plan       VARCHAR(255),
    CONSTRAINT pk_tenant PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255),
    password_hash VARCHAR(255),
    full_name     VARCHAR(255),
    role          SMALLINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE auth_refresh_token
    ADD CONSTRAINT FK_AUTHREFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);
